### ISSUE TITLE
Need Dracula Pro (Alucard) theme

### ISSUE THREAD

**Issue by ciscohack** [facelessuser/sublime-dracula-scheme#5]
Hello Expert,

Can you please make Dracula Pro (Alucard) theme also and share. Please also create theme for Kitty terminal and iterm2 terminal theme also. I really liked your inspirational theme

**Comment by facelessuser** [comment]
I've considered releasing them, see this thread: https://github.com/facelessuser/merge-dracula-theme/issues/3.

I still haven't decided. With that said, I have no intentions of branching out and doing themes for Kitty and iterm2.

**Comment by ciscohack** [comment]
Sure thank you sir

**Comment by ToxicSmurf** [comment]
@facelessuser I'd love to see the custom, independent, open-source color pallete that *you* made! I bet your *original* work is even better than the ~Vampire~ Dracula Pro theme that inspired you. @ me!

**Comment by facelessuser** [comment]
Yeah, I'm considering it. It is, in fact, using probably most of the actual Dracula color pallete, or using colors so close that the ∆E would make the colors indistinguishable from each other with the human eye.

You can't really copyright the colors, all you can do is copyright the themes, and since we have not looked at any official Pro themes, we have not taken any copyrighted material. We are simply plugging the colors into our existing themes which is based on the Sublime Text Mariana color scheme.

Alucard Pro is simply the Pro palette using the classic background and comments. It's an updated classic look that utilizes the new HSL normalized saturation/lightness palette that Pro uses.

It appears the new Dracula color scheme simply normalized saturation and lightness within the HSL color space, and sort of geometrically spaced the colors. I say sort of because the hues are not precisely spaced geometrically or symmetrically, but they are "kind of" close to being geometrically and symmetrically distanced within the HSL color space. 

- Foreground colors are all used within the official Dracula Pro site, all you have to do is extract them.
- There are some colors within the site that seem to correspond to comments. This is the only foreground color that wasn't completely obvious but after analyzing a few examples, some observations were made, and it appears there is a generalized filter that can be used to generate the comments or something that is extremely close to what the comments are:
    ```js
        "comment": "color(var(background) s(25%) l(55%))",
    ```
- Background colors are found in the images, just using a digital color meter you can extract them.
- I think there is one example of line highlighting in one of the images, based on that, a few observations were made and we came up with something generalized and practical for line highlighting and selections. I'm not 100% sure if these generalizations exactly match the official themes, but I don't care as they look good 🙂.
    ```js
        "selection": "color(var(background) s(15%) l(30%))",
        "line-highlight": "color(var(background) s(25%) l(25%))",
    ```

After that, we simply plug the new colors into our existing Dracula theme which creates the variants. We have created variants that seem to match all the Pro themes, here are just a couple:

Dracula (Pro)

<img width="1194" alt="Text - Pro" src="https://user-images.githubusercontent.com/1055125/168821350-600481bb-f418-4350-829a-d9f55d4226ae.png">

Dracula Pro (Van Helsing)

<img width="1194" alt="Text - Van Helsing" src="https://user-images.githubusercontent.com/1055125/168821387-3ffcc046-3575-4936-9ee7-1fdff4efe929.png">

**Comment by ciscohack** [comment]
if your customized build release, it will be the most loved theme... I am still waiting someday u release it

**Comment by facelessuser** [comment]
I've added Pro variants. These are based on our current work and just use the color palettes as demonstrated on the official Dracula Pro site. We do not and have not used any code from any official Dracula theme to accomplish this.
